--- #YAML:1.0
name:               Razor2-Client-Agent
version:            2.83
abstract:           Collaborative, content-based spam filtering network agent.
author:
    - Vipul Ved Prakash <mail@vipul.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    Digest::SHA1:  0
    File::Copy:    0
    File::Spec:    0
    Getopt::Long:  0
    MIME::Base64:  0
    Test::More:    0
    Time::HiRes:   0
    URI::Escape:   0
resources:
    bugtracker:   http://sourceforge.net/projects/razor
    homepage:     http://razor.sourceforge.net/
    license:      http://dev.perl.org/licenses/
    MailingList:  https://sourceforge.net/mailarchive/forum.php?forum_name=razor-users
    repository:   http://github.com/toddr/Razor2-Client-Agent
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
